### ISSUE TITLE
Use `sabre-cs-fixer fix .` instead of `lib/`

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-cs#14]
Because [php-cs-fixer automatically skips `vendor/`](https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/44effefa2dd48d39c1e7944f936a94bb5834f87e/Symfony/CS/Finder/DefaultFinder.php#L36), we can safely do:

``` sh
$ bin/sabre-cs-fixer fix --dry-run --diff .
```

It will include the `tests/` directory this way. And it's much better. All projects must update to this way of doing.

**Comment by evert** [comment]
Probably won't change that for sabre/dav, there will be too many frustrations that will be annoying to fix.

I think all the other projects would probably be fine though.

**Comment by Hywan** [comment]
@evert: What frustrations? The `tests/` directory will be fine :-). It deserves a good clean up too :-p.

**Comment by evert** [comment]
There's a lot of files that have their mock classes embedded in the same file. I know it's not right but I don't feel like fixing it yet =) so until it's fixed it will just cause builds to fail... so I'll get on this, just a little bit later =)
