### ISSUE TITLE
`protected static $attr` must not be simplified to `static $attr`

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-cs#16]
See https://travis-ci.org/fruux/sabre-katana/jobs/63172493#L289.

**Comment by evert** [comment]
Yup that's definitely wrong! dang

**Comment by Hywan** [comment]
I found a patch. Give me a second to commit.

**Comment by evert** [comment]
@Hywan are you cool with tagging this 0.0.3 ?

**Comment by Hywan** [comment]
Yup.

**Comment by Hywan** [comment]
Would you like me to do that?

**Comment by evert** [comment]
No i was just making sure you were cool with it =) doing it right now
