### ISSUE TITLE
CS change: don't align multiple variables.

### ISSUE THREAD

**Issue by evert** [fruux/sabre-cs#2]
Currently the CS fixer will change this:

``` php
$foo = 1;
$longvariable = 2;
```

to

``` php
$foo          = 1;
$longvariable = 2;
```

While I think this is totally more legible in _some_ blocks of code, especially blocks where there's many similar things being defined, I don't think it should be applied everywhere. So I'd want to remove this rule.

**Comment by Hywan** [comment]
Ok.
