### ISSUE TITLE
[Poll] Rely on pure upstream php-cs-fixer ?

### ISSUE THREAD

**Issue by DeepDiver1975** [fruux/sabre-cs#20]
sabre/cs is based on php-cs-fixer 1.1 which is by now deprecated and not compatible with latest php versions (warnings are poping up on php7.3)

Porting sabre/cs to php-cs-fixer 2.0 is quite some effort since interfaces changed. From the first look it seems all custom fixer rules need to be reimplemented.

I hereby question the necessity of these custom rules and propose to deprecate sabre/CS and use pure php-cs-fixer.

@staabm @evert

**Comment by evert** [comment]
Sounds super reasonable

**Comment by staabm** [comment]
👍
